# Generated by Django 4.2 on 2023-04-30 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoEmployee',
            fields=[
                ('em_id_key', models.AutoField(primary_key=True, serialize=False)),
                ('em_name', models.CharField(blank=True, max_length=50, null=True)),
                ('em_zone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'so_employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoType',
            fields=[
                ('type_id_key', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'so_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoOut',
            fields=[
                ('co_id_key', models.AutoField(primary_key=True, serialize=False)),
                ('co_date', models.DateField(blank=True, default=datetime.date(2023, 4, 30), null=True)),
                ('co_time_arrived', models.TimeField(auto_now=True)),
                ('co_time_dif', models.CharField(blank=True, max_length=45, null=True)),
                ('red_zone_time', models.TimeField(null=True)),
                ('yellow_zone_time', models.TimeField(null=True)),
                ('co_fk_em_id_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.soemployee')),
                ('co_fk_type_id_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sotype')),
            ],
            options={
                'db_table': 'so_outs',
                'managed': True,
            },
        ),
    ]
