# Generated by Django 4.2 on 2023-04-29 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 29), null=True),
        ),
    ]
