# Generated by Django 4.2 on 2023-04-30 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_soout_co_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soout',
            name='red_zone_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='soout',
            name='yellow_zone_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 30), null=True),
        ),
    ]
