# Generated by Django 4.2 on 2023-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_soout_co_time_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(auto_now=True),
        ),
    ]
