# Generated by Django 4.2 on 2023-05-02 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_shift_alter_soout_co_time_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default=datetime.time(8, 4, 35, 962237), null=True, verbose_name='Time Arrived'),
        ),
    ]
