# Generated by Django 4.2 on 2023-05-02 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_soout_co_time_arrived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default=datetime.time(8, 6, 26, 514394), null=True, verbose_name='Time Arrived'),
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shiftstart',
        ),
    ]
