# Generated by Django 4.2 on 2023-05-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_soout_co_date_alter_soout_co_time_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
