# Generated by Django 4.2 on 2023-05-02 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_shift_options_alter_soout_co_time_arrived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default=datetime.time(8, 16, 10, 354099), null=True, verbose_name='Time Arrived'),
        ),
    ]
