# Generated by Django 4.2 on 2023-05-01 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_soout_co_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 1), null=True),
        ),
    ]
