# Generated by Django 4.2 on 2023-05-02 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_soout_co_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soemployee',
            name='em_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='soemployee',
            name='em_zone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 1), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_fk_em_id_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.soemployee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_fk_type_id_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sotype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default=datetime.time(23, 57, 38, 231460), null=True, verbose_name='Time Arrived'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_time_dif',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Time Difference'),
        ),
    ]
