# Generated by Django 4.2 on 2023-05-02 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_soemployee_em_name_alter_soemployee_em_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soemployee',
            name='em_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 2), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_fk_em_id_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.soemployee', unique=True, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default=datetime.time(0, 16, 30, 318356), null=True, verbose_name='Time Arrived'),
        ),
        migrations.AlterField(
            model_name='sotype',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
